### ISSUE TITLE
Umbrella issue: basic features for maier.tech

### ISSUE THREAD

**Issue by maiertech** [maiertech/maier.tech-nextjs#1]
- [x] Tailwind JIT support
- [x] TypeScript support
- [x] MDX support for posts.
- [x] Tagging support (example: https://github.com/timlrx/tailwind-nextjs-starter-blog)
- [x] Sitemap (example: https://github.com/vercel/next.js/tree/canary/examples/with-sitemap)
